title: <p align="center"> Madeline Lui </p>

logo: "/images/portfolio_pp.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv_portfolio_ml.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/madeline-l-67953313a/">LinkedIn</a> |
  <a href="https://github.com/madelinelui">GitHub</a>
  </p>
  
  <p align="left">
  I am a First Class Honours Graduate, experienced in statistical computing and analysis in Python, MATLAB and R.
  <br><br>
  My projects include solar time-series forecasting, computational fMRI analysis and interactive user interfaces.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
