title: <p align="center"> Madeline Lui </p>

logo: "/images/portfolio_pp.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv_portfolio_ml.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/madeline-l-67953313a/">LinkedIn</a> |
  <a href="https://github.com/madelinelui">GitHub</a>
  </p>
  
  <p align="left">
  I am a First Class Honours Graduate, experienced in statistical computing in Python, MATLAB and R.
  <br><br>
  My data science projects include Photovoltaics time-series forecasting and Bootstrap of fMRI data.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
