title: <p align="center"> Madeline Lui </p>

logo: "/images/portfolio_pp.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv_portfolio_ml.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/madeline-l-67953313a/">LinkedIn</a> |
  <a href="https://github.com/madelinelui">GitHub</a>
  </p>
  
  <p align="left">
  I have 4 years experience in data analysis, skilled in coding and statistical methods on Python, MATLAB and R.
  <br><br>
  In my personal time, I enjoy playing classical piano - mostly Chopin - and listening to piano concertos. A current favourite is Moszkowski's Piano Concerto in E Major.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
