title: <p align="center"> Madeline Lui </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/madeline-l-67953313a/">LinkedIn</a> |
  <a href="https://github.com/madelinelui">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Data Analyst with a First Class Honours degree, experienced in statistical computing in R, Python and MATLAB.
  <br><br>
  My data science projects include Photovoltaics time-series forecasting and Bootstrap of fMRI data.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
